// gRPC services and related logic
pub mod trading_service; // This now refers to the directory engine/src/services/trading_service/

// This module will also contain the generated protobuf code.
// The build script is configured to output to src/services/generated.
// We need to make sure this generated code is properly included.
pub mod generated {
    // This will include the Rust code generated by tonic_build from trading.proto
    // The exact name 'trading' comes from the package name in trading.proto
    tonic::include_proto!("trading");
}

// Re-export generated types for easier access if needed elsewhere in the engine
pub use generated::trading_engine_client::TradingEngineClient; // Added for GUI client access
pub use generated::trading_engine_server::{TradingEngine, TradingEngineServer};
pub use generated::{
    Candle as ProtoCandle, // Renaming to avoid conflict with shared::models::Candle
    LoadCsvRequest, LoadCsvResponse,
    MarketDataRequest, MarketDataResponse,
    IndicatorRequest, IndicatorResponse,
    TradeRequest, TradeResponse,
};
